name= input("what is your name")
print("nice to meet you", name,"my name is bot")
location=input("where are you from")
print(location,"is a really cool place","I'm from spain")
number=float(input("what's your favorite number"))
my_number=3000/number
print(number,"is a incredible number","my favorite number is",my_number,"times bigger than yours")
car=input("what's your dream car")
print(car,"wow i know that car is soo cool","my dream car is a porche")
price=input("how much that car cost?")
print(price,"gee, that is spendy")
years=input("what will be a normal yearly interest for the car")
print(years, "well that's okay")
loan=input("how many years will take you for get out of the loan")
print(loan,"well it's")